### ISSUE TITLE
放到自己网站里，和在百度里绘制图层出现如下错误

### ISSUE THREAD

**Issue by Glanwu** [cmoseses/chengdu_railway_2021#1]
APP Referer校验失败。请检查该ak设置的白名单与访问所有的域名是否一致。详情查看：http://lbsyun.baidu.com/apiconsole/key#

**Comment by cmoseses** [comment]
两种解决方法：
1.可以在百度地图开发平台，换成自己的ak，然后把自己的域名加进白名单
2.可以把index.html代码直接复制进 https://lbsyun.baidu.com/jsdemo.htm#gImageGround， 然后将ak那行代码改成    <script src="//api.map.baidu.com/api?type=webgl&v=1.0&ak=您的密钥"></script>

注意这里“您的密钥”，就是“您的密钥”这4个中文字符，不用换真正的密钥。
