### ISSUE TITLE
打开地址无法显示图层

### ISSUE THREAD

**Issue by Glanwu** [cmoseses/chengdu_railway_2021#2]
https://cmoseses.github.io/ 这个地址无法显示图层，我从0.1调整到0.6都不行，开启和关闭全局科学上网都试了。

**Comment by cmoseses** [comment]
感谢@Glanwu，1. 这个repo里的访问图片的确是需要科学上网的 2  请问是你在什么浏览器呢？ 有没有尝试过科学上网后的电脑版的chrome，如果可以的话，麻烦贴一下F12里面的console报错。

**Comment by Glanwu** [comment]
谢谢你的答复，我全局用了Chrome最新，Edge最新，火狐最新都是一样的问题。如下F12的Connsole:
Error with Permissions-Policy header: Unrecognized feature: 'interest-cohort'.
DevTools failed to load source map: Could not load content for chrome-extension://fjdmkanbdloodhegphphhklnjfngoffa/lib/browser-polyfill.min.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load source map: Could not load content for chrome-extension://ncennffkjdiamlpmcbajkmaiiiddgioo/js/xl-content.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
api?type=webgl&v=1.0&ak=QXtzrZOE57w779ooLpehwjNIFUSmrg0b:1 A parser-blocking, cross site (i.e. different eTLD+1) script, https://api.map.baidu.com/getscript?type=webgl&v=1.0&ak=QXtzrZOE57w779ooLpehwjNIFUSmrg0b&services=&t=20210528194133, is invoked via document.write. The network request for this script MAY be blocked by the browser in this or a future page load due to poor network connectivity. If blocked in this page load, it will be confirmed in a subsequent console message. See https://www.chromestatus.com/feature/5718547946799104 for more details.
(anonymous) @ api?type=webgl&v=1.0&ak=QXtzrZOE57w779ooLpehwjNIFUSmrg0b:1
(anonymous) @ api?type=webgl&v=1.0&ak=QXtzrZOE57w779ooLpehwjNIFUSmrg0b:1
api?type=webgl&v=1.0&ak=QXtzrZOE57w779ooLpehwjNIFUSmrg0b:1 A parser-blocking, cross site (i.e. different eTLD+1) script, https://api.map.baidu.com/getscript?type=webgl&v=1.0&ak=QXtzrZOE57w779ooLpehwjNIFUSmrg0b&services=&t=20210528194133, is invoked via document.write. The network request for this script MAY be blocked by the browser in this or a future page load due to poor network connectivity. If blocked in this page load, it will be confirmed in a subsequent console message. See https://www.chromestatus.com/feature/5718547946799104 for more details.
(anonymous) @ api?type=webgl&v=1.0&ak=QXtzrZOE57w779ooLpehwjNIFUSmrg0b:1
(anonymous) @ api?type=webgl&v=1.0&ak=QXtzrZOE57w779ooLpehwjNIFUSmrg0b:1
(index):74 102.801618 30.024593 105.14898602739727 32.146592999999996
VM102:1 WebGL: INVALID_VALUE: texImage2D: width or height out of range
eR @ VM102:1
drawGroundOverlay @ VM105:1
draw @ VM105:1
_updateFrame @ VM105:1
eval @ VM105:1
requestAnimationFrame (async)
_updateFrame @ VM105:1
eval @ VM105:1
requestAnimationFrame (async)
startRenderThread @ VM105:1
_init @ VM105:1
y @ VM105:1
eval @ VM105:1
_asyncRegister @ getscript?type=webgl&v=1.0&ak=QXtzrZOE57w779ooLpehwjNIFUSmrg0b&services=&t=20210528194133:1
(anonymous) @ getscript?type=webgl&v=1.0&ak=QXtzrZOE57w779ooLpehwjNIFUSmrg0b&services=&t=20210528194133:1
run @ getscript?type=webgl&v=1.0&ak=QXtzrZOE57w779ooLpehwjNIFUSmrg0b&services=&t=20210528194133:1
window._jsload @ getscript?type=webgl&v=1.0&ak=QXtzrZOE57w779ooLpehwjNIFUSmrg0b&services=&t=20210528194133:1
(anonymous) @ getmodules?v=1.0&type=webgl&mod=glcommon_5i3khj,marker_pihjdc,poly_adbmm2,mapgl_bv4znh,oppcgl_u5jh4a,scommon_phcj0k,control_dypiur:4
abclite-2063-s.js:1 [Deprecation] RTP data channels are no longer supported. The "RtpDataChannels" constraint is currently ignored, and may cause an error at a later date.

**Comment by cmoseses** [comment]
@Glanwu  从 下面这个信息看出可能是浏览器或者插件 block了一个方法
```
https://api.map.baidu.com/getscript?type=webgl&v=1.0&ak=QXtzrZOE57w779ooLpehwjNIFUSmrg0b&services=&t=20210528194133, is invoked via document.write. The network request for this script MAY be blocked by the browser in this or a future page load due to poor network connectivity. If blocked in this page load, it will be confirmed in a subsequent console message
```

1. 请问可以正常访问https://lbsyun.baidu.com/jsdemo.htm#gImageGround  吗？  
2. 如果把index.html里面的代码帖1里面的地址进去，然后将ak替换成  “您的秘钥” 四个中文，  可以加载出成都地图和图层吗？
3. 如果科学上网后，尝试用chrome匿名模式打开https://cmoseses.github.io/   会报什么错呢？

**Comment by Glanwu** [comment]
以下都全局科学
1.可以打开，但是图层无法加载
2.试了，一样无法加载图层
3.匿名模式打开后F12如下：
api?type=webgl&v=1.0&ak=QXtzrZOE57w779ooLpehwjNIFUSmrg0b:1 A parser-blocking, cross site (i.e. different eTLD+1) script, https://api.map.baidu.com/getscript?type=webgl&v=1.0&ak=QXtzrZOE57w779ooLpehwjNIFUSmrg0b&services=&t=20210528194133, is invoked via document.write. The network request for this script MAY be blocked by the browser in this or a future page load due to poor network connectivity. If blocked in this page load, it will be confirmed in a subsequent console message. See https://www.chromestatus.com/feature/5718547946799104 for more details.
(anonymous) @ api?type=webgl&v=1.0&ak=QXtzrZOE57w779ooLpehwjNIFUSmrg0b:1
api?type=webgl&v=1.0&ak=QXtzrZOE57w779ooLpehwjNIFUSmrg0b:1 A parser-blocking, cross site (i.e. different eTLD+1) script, https://api.map.baidu.com/getscript?type=webgl&v=1.0&ak=QXtzrZOE57w779ooLpehwjNIFUSmrg0b&services=&t=20210528194133, is invoked via document.write. The network request for this script MAY be blocked by the browser in this or a future page load due to poor network connectivity. If blocked in this page load, it will be confirmed in a subsequent console message. See https://www.chromestatus.com/feature/5718547946799104 for more details.
(anonymous) @ api?type=webgl&v=1.0&ak=QXtzrZOE57w779ooLpehwjNIFUSmrg0b:1
(index):74 102.801618 30.024593 105.14898602739727 32.146592999999996
abclite-2063-s.js:1 [Deprecation] RTP data channels are no longer supported. The "RtpDataChannels" constraint is currently ignored, and may cause an error at a later date.
(anonymous) @ abclite-2063-s.js:1
VM15:1 WebGL: INVALID_VALUE: texImage2D: width or height out of range
eR @ VM15:1
4(index):74 102.801618 30.024593 105.14898602739727 32.146592999999996

**Comment by cmoseses** [comment]
@Glanwu  如果第1个可以打开，但是图层报错，可能就是百度地图的问题了哈，因为是百度地图官方的实例。
这里还是展示一下正常打开 第1个链接的样子。
![image](https://user-images.githubusercontent.com/12706159/125417518-013e9ebb-c08d-46e8-9b13-0900df8c9f95.png)

参考一下这个解决方案呢？
https://www.cnblogs.com/mmzuo-798/p/10411401.html

**Comment by Glanwu** [comment]
好的，第一个打开的确如你图所示，谢谢，虽然我换了电脑和浏览器还是没有解决。
另外请问你在其他电脑上打开https://cmoseses.github.io/ 正常么？谢谢

**Comment by Glanwu** [comment]
我在新的电脑上居然能打开了，也不知是什么原因，谢谢你！
